### PR TITLE
Allow to set pull request custom title and body

### PR DESCRIPTION
**Pull request by eko**
Hi,

We are using your GitOps rules and would like to add some arguments to the `@com_adobe_rules_gitops//gitops/prer:create_gitops_prs` in order to allow settings a custom title and/or body pull request.

## Description

By default, it continues to act as it is for now by settings the following as title and body: `GitOps deployment <branch>`, but you can also specify:

* `-gitops_pr_title "<your pull request title>"`
* `-gitops_pr_body "<your pull request body>"`

This would be useful for us in order to display a changelog in the pull request body.

## Related Issue

https://github.com/adobe/rules_gitops/issues/136

## Motivation and Context

We would like to add custom information to the pull request such as a changelog.

## How Has This Been Tested?

I've tested it by forking the project and using it in my Bazel project.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by michaelschiff — APPROVED** [review]
Thanks for the contribution! LGTM

**Review by kzadorozhny — APPROVED** [review]

**Comment by eko** [comment]
Hello, do you think we could have this merged and released soon?

**Comment by michaelschiff** [comment]
Sorry for the delay, thank you again for the contribution!

**Comment by eko** [comment]
No problem, thank you @michaelschiff! :)

**Comment by eko** [comment]
@michaelschiff Could you also please tag a new release with this addition?

**Pull request merged**
