### PR TITLE
add nil check to ready callback

### PR DESCRIPTION
**Pull request by davidgmonical**
## Description

Add a `nil` check in case the optional `ReadyCallback` is not provided

## Motivation and Context

Since `ReadyCallback` is optional it should not cause a panic if it is not provided.

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by michaelschiff** [comment]
Thanks for the contribution! Can you add a test for this case as well? you may need to separate them into separate sub-packages of `testing/it_sidecar/client` since each will have a different `TestMain`

**Review by kzadorozhny — APPROVED** [review]

**Review by kzadorozhny — CHANGES_REQUESTED** [review]
Please avoid creating separate subpackage. I think it is possible to add no callback test scenario in the `sidecar_client_test.go` test.

**Comment by kzadorozhny** [comment]
> Please avoid creating separate subpackage. I think it is possible to add no callback test scenario in the `sidecar_client_test.go` test.
@davidgmonical, @michaelschiff has clarified to me the reason to have a separate package per test. I think, we should re-organize client tests a bit:
- create two test packages `testing/it_sidecar/client/test_callback` and `testing/it_sidecar/client/test_no_callback` and move `sidecar_client_test.go` to `test_callback` subpackage.
- consider reusing `noop.setup` script, not to copy it in every test package.

**Comment by davidgmonical** [comment]
> > Please avoid creating separate subpackage. I think it is possible to add no callback test scenario in the `sidecar_client_test.go` test.
> > @davidgmonical, @michaelschiff has clarified to me the reason to have a separate package per test. I think, we should re-organize client tests a bit:
> 
> * create two test packages `testing/it_sidecar/client/test_callback` and `testing/it_sidecar/client/test_no_callback` and move `sidecar_client_test.go` to `test_callback` subpackage.
> * consider reusing `noop.setup` script, not to copy it in every test package.

Reorganized them as specified with 2 separate packages and reusing `noop.setup`. Let me know if it needs any additional changes

**Review by kzadorozhny — DISMISSED** [review]

**Review by kzadorozhny — APPROVED** [review]

**Comment by kzadorozhny** [comment]
Please run `baze run //:buildifier-fix` and commit the changes.

**Comment by kzadorozhny** [comment]
Please, rebase/upmerge master. E2E tests were broken.

**Review by kzadorozhny — APPROVED** [review]

**Pull request merged**
