### PR TITLE
Update push.bzl

### PR DESCRIPTION
**Pull request by uajith**
Removing `tag` as well. 
On Bazel 5.0, tag also became obsolete.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by uajith** [comment]
The error seen in Bazel 5.0 is

image

The error says
```sh
Error: unexpected keywords stamp, stamp, stamp, stamp_inputs, tag in call to instantiate provider PushInfo
```

This means we need to delete the keyword `tag` as well from the mentioned file.

**Comment by uajith** [comment]
Detailed error : https://jenkins.dev.k8s.tubemogul.info/blue/organizations/jenkins/monorepo%2Ftm-repo/detail/feature%2FCICD-177-Bazel5_Upgrade/21/pipeline/

**Review by kzadorozhny — CHANGES_REQUESTED** [review]
Please resolve the build failures and add `5.0.0` to the CI test matrix.

**Review by kzadorozhny — CHANGES_REQUESTED** [review]
Please remove duplicate `exe[PushInfo].repository` output from the push script output

**Review by kzadorozhny — APPROVED** [review]

**Pull request merged**
